### ISSUE TITLE
File %s does not exist.

### ISSUE THREAD

**Issue by killerking5** [quanyang/Taint-em-All#1]
Hello! I use command 'python cli.py filepath' in cmd,but it gives an error like "File %s does not exist",it is an exception wrote in PHPEngine.py in line 58. I cann't find the reason.Can you give me any suggest? In addition，the link named "http://taint.spro.ink/" is broken.

**Comment by quanyang** [comment]
Could you share the PHP file you are trying to scan?

**Comment by killerking5** [comment]
The object i want to examine is an open source WEB application written in PHP.I add it to the attachment.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Quan Yang"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月27日(星期一) 下午3:31
收件人:&nbsp;"quanyang/Taint-em-All"<Taint-em-All@noreply.github.com&gt;;
抄送:&nbsp;"刘敏"<1348051169@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [quanyang/Taint-em-All] File %s does not exist. (#1)





 
Could you share the PHP file you are trying to scan?

**Comment by killerking5** [comment]
Could you please send me a copy of your source code? I want to do second-order injection detection based on your research, just for learning research.Thank you very much!




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Quan Yang"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月27日(星期一) 下午3:31
收件人:&nbsp;"quanyang/Taint-em-All"<Taint-em-All@noreply.github.com&gt;;
抄送:&nbsp;"刘敏"<1348051169@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [quanyang/Taint-em-All] File %s does not exist. (#1)





 
Could you share the PHP file you are trying to scan?

**Comment by RandomRobbieBF** [comment]
Same error for me.
```
wordpress@wordpress:~/Taint-em-All$ python2.7 cli.py ~/Taint-em-All/test.php
/bin/sh: 1: php: not found
Traceback (most recent call last):
  File "cli.py", line 39, in <module>
    main()
  File "cli.py", line 26, in main
    scanFile(staticTaintAnalysisVisitor, inputFile)
  File "cli.py", line 11, in scanFile
    CFGForest = engine.generateCFG(inputFile)
  File "/home/wordpress/Taint-em-All/Engine/PHPEngine.py", line 53, in generateCFG
    raise Exception("File %s does not exist." % path)
Exception: File /home/wordpress/Taint-em-All/test.php does not exist.
```
test.php
---
```
<?php

$a = file_get_content($_REQUEST['test']);
echo $a;

?>
```

**Comment by RandomRobbieBF** [comment]
might need `php-cli` installed to run this.

**Comment by quanyang** [comment]
Thanks @RandomRobbieBF, I updated the readme with the instruction to install php-cli.
